name: webtools-ci-v2

on:
  push:
    branches:
      - $default-branch
      - pages-workflow

jobs:
  build-deploy-pages:
    permissions:
      contents: read
      id-token: write
      pages: write

    name: Build GitHub Pages
    uses: ./.github/workflows/webtools.yaml
    with:
      dist: ./johndoe.com/dist
      deploy_branch: test-pages-workflow/johndoe.com
      wipe_deploy_branch: true
      cname: johndoe.com
